const fs = require("fs");
const path = require("path");

const projectRoot = path.resolve(__dirname, "..");
const sourceDirectory = path.join(projectRoot, "content", "blogs");
const publicAssetDirectory = path.join(projectRoot, "public", "blog-assets");
const manifestPath = path.join(projectRoot, "src", "blogs.generated.js");
const requiredFields = [
  "id",
  "title",
  "publishedAt",
  "kicker",
  "readTime",
  "excerpt",
  "topics",
  "sourceUrl",
];

function parseValue(value) {
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return JSON.parse(trimmed);
  }
  return trimmed;
}

function prepareImages(body, sourcePath, slug) {
  const imagePattern = /(!\[[^\]]*\]\()(<[^>]+>|[^\s)]+)(\s+(?:"[^"]*"|'[^']*'))?(\))/g;

  return body.replace(imagePattern, (image, prefix, rawUrl, title = "", suffix) => {
    const imageUrl = rawUrl.startsWith("<") ? rawUrl.slice(1, -1) : rawUrl;
    if (/^(?:[a-z][a-z\d+.-]*:|\/|#)/i.test(imageUrl)) return image;

    const [imagePath] = imageUrl.split(/[?#]/, 1);
    const sourceImagePath = path.resolve(path.dirname(sourcePath), decodeURIComponent(imagePath));
    const relativeToContent = path.relative(sourceDirectory, sourceImagePath);

    if (relativeToContent.startsWith("..") || path.isAbsolute(relativeToContent)) {
      throw new Error(`${path.basename(sourcePath)}: image must live inside content/blogs: ${imageUrl}`);
    }
    if (!fs.existsSync(sourceImagePath) || !fs.statSync(sourceImagePath).isFile()) {
      throw new Error(`${path.basename(sourcePath)}: image not found: ${imageUrl}`);
    }

    const outputDirectory = path.join(publicAssetDirectory, slug);
    const outputFilename = path.basename(sourceImagePath);
    fs.mkdirSync(outputDirectory, { recursive: true });
    fs.copyFileSync(sourceImagePath, path.join(outputDirectory, outputFilename));

    return `${prefix}/blog-assets/${slug}/${encodeURIComponent(outputFilename)}${title}${suffix}`;
  });
}

function parseDocument(filename) {
  const sourcePath = path.join(sourceDirectory, filename);
  const source = fs.readFileSync(sourcePath, "utf8").replace(/\r\n/g, "\n");
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);

  if (!match) {
    throw new Error(`${filename}: expected YAML-style frontmatter wrapped in --- lines`);
  }

  const metadata = {};
  for (const line of match[1].split("\n")) {
    if (!line.trim()) continue;
    const separator = line.indexOf(":");
    if (separator === -1) {
      throw new Error(`${filename}: invalid frontmatter line: ${line}`);
    }
    metadata[line.slice(0, separator).trim()] = parseValue(line.slice(separator + 1));
  }

  for (const field of requiredFields) {
    if (!metadata[field]) throw new Error(`${filename}: missing required frontmatter field '${field}'`);
  }

  if (!/^\d{4}-\d{2}-\d{2}$/.test(metadata.publishedAt)) {
    throw new Error(`${filename}: publishedAt must use YYYY-MM-DD`);
  }

  const slug = path.basename(filename, ".md");
  const body = prepareImages(`${match[2].trim()}\n`, sourcePath, slug);
  const publishedDate = new Date(`${metadata.publishedAt}T00:00:00Z`);

  return {
    metadata: {
      id: metadata.id,
      slug,
      kicker: metadata.kicker,
      title: metadata.title,
      publishedAt: metadata.publishedAt,
      publishedLabel: publishedDate.toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
        timeZone: "UTC",
      }),
      readTime: metadata.readTime,
      excerpt: metadata.excerpt,
      topics: metadata.topics.split(",").map((topic) => topic.trim()).filter(Boolean),
      sourceUrl: metadata.sourceUrl,
      body,
    },
  };
}

function syncBlogs() {
  const documents = fs
    .readdirSync(sourceDirectory)
    .filter((filename) => filename.endsWith(".md"))
    .map(parseDocument)
    .sort((left, right) => right.metadata.publishedAt.localeCompare(left.metadata.publishedAt));

  if (!documents.length) throw new Error("No Markdown articles found in content/blogs");

  const blogs = documents.map((document, index) => ({
    ...document.metadata,
    index: String(index + 1).padStart(2, "0"),
  }));
  const manifest = `// Generated by scripts/sync-blogs.js. Edit content/blogs/*.md instead.\nexport const blogs = ${JSON.stringify(blogs, null, 2)};\n`;
  fs.writeFileSync(manifestPath, manifest);

  console.log(`Synced ${documents.length} blog${documents.length === 1 ? "" : "s"}.`);
}

syncBlogs();
